name: openmmlab
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2023.5.7=py38h06a4308_0
  - cffi=1.15.0=py38hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.1=py38h774aba0_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py38h06a4308_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=py38h06a4308_0
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.7.0.149=0
  - libcurand=10.3.3.53=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py38h7f8727e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py38h06a4308_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py38h06a4308_1
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1u=h7f8727e_0
  - pillow=9.0.1=py38h22f2fdc_0
  - pip=23.1.2=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - pytorch=2.0.1=py3.8_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.29.0=py38h06a4308_0
  - setuptools=67.8.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=hc218d9a_0
  - sympy=1.11.1=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.0.2=py38_cu117
  - torchtriton=2.0.0=py38
  - torchvision=0.15.2=py38_cu117
  - typing_extensions=4.6.3=py38h06a4308_0
  - urllib3=1.26.16=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - addict==2.4.0
    - appdirs==1.4.4
    - attributee==0.1.8
    - click==8.1.4
    - colorama==0.4.6
    - contourpy==1.1.0
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - dotdict==0.1
    - dotty-dict==1.3.1
    - einops==0.6.1
    - fonttools==4.40.0
    - fsspec==2023.6.0
    - ftfy==6.1.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - huggingface-hub==0.16.4
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - joblib==1.3.1
    - kiwisolver==1.4.4
    - lap==0.4.0
    - markdown==3.4.3
    - markdown-it-py==3.0.0
    - mat4py==0.5.0
    - matplotlib==3.7.2
    - mdurl==0.1.2
    - mmcls==0.25.0
    - mmcv==2.0.1
    - mmdet==3.1.0
    - mmengine==0.8.1
    - mmpretrain==1.0.0
    - mmtrack==0.14.0
    - model-index==0.1.11
    - modelindex==0.0.2
    - motmetrics==1.4.0
    - nvidia-dlprof==1.8.0
    - nvidia-nsys-cli==2021.3.2.12
    - nvidia-pyindex==1.0.9
    - opencv-python==4.8.0.74
    - opendatalab==0.0.9
    - openmim==0.3.9
    - ordered-set==4.1.0
    - packaging==23.1
    - pandas==1.3.5
    - pathtools==0.1.2
    - platformdirs==3.8.1
    - prettytable==3.8.0
    - protobuf==4.23.4
    - psutil==5.9.5
    - pycocotools==2.0.6
    - pycryptodome==3.18.0
    - pygments==2.15.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0
    - regex==2023.6.3
    - rich==13.4.2
    - safetensors==0.3.1
    - scipy==1.7.3
    - seaborn==0.12.2
    - sentry-sdk==1.28.0
    - setproctitle==1.3.2
    - shapely==2.0.1
    - smmap==5.0.0
    - tabulate==0.9.0
    - termcolor==2.3.0
    - timm==0.9.2
    - tomli==2.0.1
    - torch-pruning==1.2.1
    - tqdm==4.65.0
    - tzdata==2023.3
    - wandb==0.15.5
    - wcwidth==0.2.6
    - wget==3.2
    - xmltodict==0.13.0
    - yapf==0.40.1
    - zipp==3.15.0
prefix: /home/bartels/.conda/envs/openmmlab
